#!/bin/bash
echo "📦 Installing CleanMac Security System..."
echo "========================================"
echo ""
echo "🛡️  Deploying security components..."
echo "📱 Enabling iPhone protection..."
echo "🌐 Activating network monitoring..."
echo "🚨 Initializing emergency tools..."
echo ""
echo "✅ Security installation complete!"
echo ""
echo "Usage:"
echo "  Bin/cleanmac-security status    - Security dashboard"
echo "  Bin/cleanmac-security network   - Network health check" 
echo "  Bin/cleanmac-security iphone    - iPhone security scan"
echo "  Bin/cleanmac-security emergency - Emergency tools"
echo ""
