name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          chmod +x ./scripts/test.sh
          ./scripts/test.sh || echo "No tests yet, continuing..."
      - name: Security scan
        run: |
          echo "Security checks would run here"
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build verification
        run: |
          chmod +x ./cleanmac
          ./cleanmac --version || echo "Version check not implemented"
